// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJRwJtZEGe_fVsBHNu2iNcwh_m1REF1n8',
    appId: '1:1097246653921:web:21e440a2174a1d1c48a6a0',
    messagingSenderId: '1097246653921',
    projectId: 'javinsensestudios-jobs',
    authDomain: 'javinsensestudios-jobs.firebaseapp.com',
    databaseURL: 'https://javinsensestudios-jobs-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'javinsensestudios-jobs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXFoPsEizXu-L5LHqcjuc03IL9OmbqbGU',
    appId: '1:1097246653921:android:600efb5ce889c6a748a6a0',
    messagingSenderId: '1097246653921',
    projectId: 'javinsensestudios-jobs',
    databaseURL: 'https://javinsensestudios-jobs-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'javinsensestudios-jobs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8gkFmURzki_lN8dk9M6qAfE2yLDlC_-U',
    appId: '1:1097246653921:ios:e56d01dcbbed367f48a6a0',
    messagingSenderId: '1097246653921',
    projectId: 'javinsensestudios-jobs',
    databaseURL: 'https://javinsensestudios-jobs-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'javinsensestudios-jobs.appspot.com',
    iosClientId: '1097246653921-ki04irlsrd227fpl05b6hlt8u7m4td1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobs',
  );
}
